[program:qa365-default-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/qa365/artisan queue:work redis --queue=default,notifications --sleep=3 --tries=3 --timeout=300 --max-time=3600
directory=/var/www/qa365
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/qa365/storage/logs/worker-default.log
stopwaitsecs=360

[program:qa365-ai-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/qa365/artisan queue:work redis --queue=transcription,ai-scoring,insights --sleep=3 --tries=3 --timeout=720 --max-time=3600
directory=/var/www/qa365
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/qa365/storage/logs/worker-ai.log
stopwaitsecs=780
