[program:qa365-default-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/qa365/artisan queue:work redis --queue=default,notifications --sleep=3 --tries=3 --timeout=300 --max-time=3600
directory=/var/www/qa365
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/qa365/storage/logs/worker-default.log
stopwaitsecs=360

[program:qa365-transcription-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/qa365/artisan queue:work redis --queue=transcription --sleep=3 --tries=60 --timeout=900 --max-time=3600
directory=/var/www/qa365
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=3
redirect_stderr=true
stdout_logfile=/var/www/qa365/storage/logs/worker-transcription-%(process_num)02d.log
stopwaitsecs=960

[program:qa365-ai-scoring-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/qa365/artisan queue:work redis --queue=ai-scoring --sleep=3 --tries=60 --timeout=900 --max-time=3600
directory=/var/www/qa365
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=5
redirect_stderr=true
stdout_logfile=/var/www/qa365/storage/logs/worker-ai-scoring-%(process_num)02d.log
stopwaitsecs=960
